FEAT(slide): Sort of get the edit slide form talking to the store correctly?
We can edit a record, and it writes the changes to the correct part of
the local state, through the simple expedient of cheating. We are
getting the following error glob when we try to save a record, however:

```
xhr.js:175 GET http://localhost:8080/api/slides/undefined 500 (Internal
Server Error)
...
slide.js:34 Error: Request failed with status code 500
    at createError (createError.js:15)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:77)
EditSlideForm.jsx:71
newSingleSlideAction: undefined
EditSlideForm.jsx:72 Uncaught (in promise) TypeError: Cannot read property
'singleSlide' of undefined
    at EditSlideForm.jsx:72
    at <anonymous>
```